In [22]:
# numpy array 사용
import numpy as np

# Python의 리스트로부터 변환하여 사용
my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

In [23]:
# アレイを表示する
my_array1


array([1, 2, 3, 4])

In [24]:
type(my_array1)

numpy.ndarray

In [21]:
type(my_list1)

list

In [29]:
# 別のアレイを作って
my_list2 = [11,22,33,44]

# リストのリストを作成
my_lists = [my_list1,my_list2]

In [30]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [31]:
# 2차원 list를 이용해서 array만들기
my_array2 = np.array(my_lists)

my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [32]:
# array size
my_array2.shape

(2, 4)

In [39]:
# array size 2x4
my_array2.size

8

In [33]:
# array data type
my_array2.dtype

dtype('int64')

In [35]:
# special array

# all zero, size is 5
zero_array = np.zeros(5)
zero_array

array([ 0.,  0.,  0.,  0.,  0.])

In [36]:
# shape of array, 차원
zero_array.shape

(5,)

In [37]:
# 크키
zero_array.size

5

In [8]:
my_zeros_array.dtype

dtype('float64')

In [9]:
# 전부 1인 array
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [46]:
# 빈 array

np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [47]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [48]:
np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [49]:
# 단위 행렬 I（dentity array）
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [50]:
# arange 
np.arange(5)

array([0, 1, 2, 3, 4])

In [54]:
# arrange(start, end, step) except end
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [55]:
np.arange(1,10,3)

array([1, 4, 7])